version: '2'

services:
  omeka-s:
    build: ./
    image: doovoo/omeka-s:3.2.0
    #ports:
    #    - "0.0.0.0:80:80"
    volumes:
      - ~/volume/omeka-s/modules/:/var/www/html/modules/
      - ~/volume/omeka-s/themes/custom/:/var/www/html/themes/custom/
    restart: always

